# -*- coding: utf-8 -*-
"""Problema1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qQVX_Qvsb4O0wGog5Smn2SjtsfDa7GNM

# Hello

Implemente un programa que imprima un saludo simple para el usuario, como se indica a continuación.

<img src='./img/ejercicio1.PNG'>
<!-- "C:\Users\gdelgadr\Desktop\JoinProcess\PYTHON-FUNDAMENTOS-JOINPROCESS\Modulo1\Ejercicios\img\ejercicio1.PNG" -->

## Especificaciones

Genere un archivo llamado <b>hello.py</b> , el cual contendrá un programa que solicita al usuario su nombre, y luego imprima <b>hello, "nombre" </b> , donde "nombre" es el nombre proporcionado.

<img src='./img/ejercicio1.PNG'>
<!-- "C:\Users\gdelgadr\Desktop\JoinProcess\PYTHON-FUNDAMENTOS-JOINPROCESS\Modulo1\Ejercicios\img\ejercicio1.PNG" -->

## Pruebas

Asegúrese de probar su código para cada uno de los siguientes.

- Ejecute su programa como python hello.py y espere a que se le solicite la entrada. Escribe Emmay presiona enter. Su programa debería generar hello, Emma.
- Ejecute su programa como python hello.py y espere a que se le solicite la entrada. Escribe Rodrigoy presiona enter. Su programa debería generar hello, Rodrigo.
"""

print('What is your name?')
nombre=input()
print (f"hello,{nombre}")