# -*- coding: utf-8 -*-
"""Problemas Diversos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JBwwBEhTePbKT5HVTzFacy9Ro8c4InEg

# PROBLEMAS DIVERSOS

<h3>1.</h3>
Imagina que acabas de abrir una nueva cuenta de ahorros que te ofrece el 4% de interés al año. Estos ahorros debido a intereses, que no se cobran hasta finales de año, se te añaden al balance final de tu cuenta de ahorros. Escribir un programa que comience leyendo la cantidad de dinero depositada en la cuenta de ahorros, introducida por el usuario. Después el programa debe calcular y mostrar por pantalla la cantidad de ahorros tras el primer, segundo y tercer años. Redondear cada cantidad a dos decimales.
"""

deposit=float(input("Enter the 1st deposit:"))
Interest=0.04
TotalMoneyOneYear=deposit*(1+Interest)
print("Money in the first year:"+str(round(TotalMoneyOneYear,2)))

TotalMoneyTwoYear=TotalMoneyOneYear*(1+Interest)
print("Money in the second year:"+str(round(TotalMoneyTwoYear,2)))

TotalMoneyThreeYear=TotalMoneyTwoYear*(1+Interest)
print("Money in the third year:"+str(round(TotalMoneyThreeYear,2)))

"""### 2.
Escriba un programa que pida los coeficientes de una ecuación de segundo grado <code>(a x² + b x + c = 0)</code> y escriba la solución.

Se recuerda que una ecuación de segundo grado puede no tener solución, tener una solución única, tener dos soluciones o que todos los números sean solución.

<img src='https://i.pinimg.com/originals/d3/f7/01/d3f701528ad56ce0f5a98d7c91722fd7.png'>

Su programa debe indicar:
- En caso la ecuación cuadrática tenga solución real, su programa debe brindar la solución
- En caso su ecuación no tenga solución real, su programa debe brindar un mensaje que diga "Ecuación no presenta solución real"
"""

def EcuacionCuadratica():
  print("Ecuación AX^2 +BX+C=0")
  a=float(input("Escriba el valor del coeficiente a:"))
  b=float(input("Escriba el valor del coeficiente b:"))
  c=float(input("Escriba el valor del coeficiente c:"))

  if a == b == c:
    print("Todos los números son solución.")
  elif a == b == 0:
    print("La ecuación no tiene solución.")
  elif a == 0 :
    print("La ecuación tiene una solución.")
  else:
    d=b*b-4*a*c
    if d<0:
      print("La ecuación no tiene solución real.")
    elif d==0:
      print(f"La ecuación no tiene solución real:{-b/(2*a)}")
    else:
      print(f"La ecuación tiene dos soluciones:{(-b - d ** 0.5) / (2 * a)} y {(-b + d ** 0.5) / (2 * a)}"   )

if_name_ = "_EcuacionCuadratica_"
EcuacionCuadratica()