# -*- coding: utf-8 -*-
"""Problemas Diversos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UoEmXhkZ7pWiy-p8uQoIBKwuBFyO9ruB

# PROBLEMAS DIVERSOS

<h3>1.</h3>
Realizar una función que permita la carga de n alumnos. Por cada alumno se deberá preguntar el nombre completo y permitir el ingreso de 3 notas. Las notas deben estar comprendidas entre 0 y 20. Devolver el listado de alumnos.
"""

cantidad = int(input("Ingrese la cantidad de alumnos a registrar : "))
cantidad

lista_alumnos = []
# solicito n veces un alumno por teclado
for i in range(cantidad):
    # dicx vacio
    dicx_alumnos = {}
    
    # ingreso datos
    dicx_alumnos['alumno'] = input(f'Ingrese el {i+1} alumno: ')
    
    nota1 = int(input('ingrese la nota 1: '))
    nota2 = int(input('ingrese la nota 2: '))
    nota3 = int(input('ingrese la nota 3: '))
    
    dicx_alumnos['notas'] = [nota1,nota2,nota3]
    
    # añado alumno a listado
    lista_alumnos.append(dicx_alumnos)

lista_alumnos

"""### 2.
Definir una función que dado un listado de alumnos evalúe cuántos aprobaron y cuántos desaprobaron, teniendo en cuenta que se aprueba con 4. La nota será el promedio de las 3 notas para cada alumno.
"""

aplazados = aprobados = notables = 0
 
while True:
	nota = float(input('Ingrese nota (0 para terminar):'))
	if nota == 0:
		break
 
	if nota > 10:
		continue
	else:
		if nota < 4:
			aplazados += 1
		elif nota >= 4 and nota <=7:
			aprobados += 1
		elif nota > 7 and nota <= 10:
			notables += 1
 
print('\nNumero de aprobados %d' %aprobados)
print('Numero de aplazados %d' %aplazados)
print('Numero de notables %d' %notables)

"""3.Informar el promedio de nota del curso total.

"""

data = [int(input('Ingrese nota1:')), int(input('Ingrese nota1:')), int(input('Ingrese nota1:')), int(input('Ingrese nota1:')), int(input('Ingrese nota1:')), int(input('Ingrese nota1:'))]
mean = sum(data)/float(len(data))
print(mean)

"""4.Realizar una función que indique quién tuvo el promedio más alto y quién tuvo la nota promedio más baja."""

notas = []
for indice in range(1,6):
	while True:
		nota = int(input("Introduce la nota %d:" % indice))
		if nota>=0 and nota<=20: break
	notas.append(nota)

# Muestro resultados

print("Notas: ",end="")
for nota in notas:
	print(nota," ",end="")
print()
print("Nota media: ",sum(notas)/len(notas))
print("Nota max: ",max(notas))
print("Nota min: ",min(notas))

"""### 5.
Realizar una función que permita buscar un alumno por nombre, siendo el nombre completo o parcial, y devuelva una lista con los n alumnos que concuerden con ese nombre junto con todos sus datos, incluido el promedio de sus notas.
"""

# Queremos guardar los nombres y la edades de los alumnos de un curso. 
# Realiza un programa que introduzca el nombre y la edad de cada alumno. 
# El proceso de lectura de datos terminará cuando se introduzca como nombre 
# un asterisco (*) Al finalizar se mostrar los siguientes datos:
#  * Todos lo alumnos mayores de edad.
#  * Los alumnos mayores (los que tienen más edad)

nombres = []
notas = []
# Inicializo las listas hasta que introduzca un "*" 
while True:	
	nombre = input("Dime el nombre de un alumno:")
	if nombre != "*":
		nombres.append(nombre)
		notas.append(int(input("Dime su nota:")))
	if nombre == "*": break;	

# Calcular la nota máxima
nota_max = max(notas)
# Alumnos con notas mayores 
print("=======================")
print("Alumnos con notas  aprobatorias ")
print("=======================")
for nombre,nota in zip(nombres,notas):
	if nota >= 10:
		print(nombre)
	
# Alumnos mayores 
print("=======================")
print("Alumnos mejores notas")
print("=======================")
for nombre,nota in zip(nombres,notas):
	if nota == nota_max:
		print(nombre)